### ISSUE TITLE
Installing on OS X - fails if gfortran is not present

### ISSUE THREAD

**Issue by elnjensen** [iancze/DiskJockey#12]
During the install, building Dierckx.jl fails because it tries to find gfortran, which is not installed by default on OS X. 

Solution:  Instructions could point to pre-built Mac gfortran from http://hpc.sourceforge.net/ .

**Comment by iancze** [comment]
Perhaps there is a smooth way to automatically install the GCC/gfortran packages, but for now I just included a note in the README. Thanks.
