### ISSUE TITLE
On OS X, command-line julia not installed by default when julia is installed

### ISSUE THREAD

**Issue by elnjensen** [iancze/DiskJockey#13]
Installing Julia on OS X only installs into /Applications, so the julia binary is not in the PATH.  So running 

DJInitialize.jl --version

fails with "julia: no such file or directory"

Solution: instructions could point to https://en.wikibooks.org/wiki/Introducing_Julia/Getting_started#Running_directly_from_terminal  which give various ways to set this up (alias or symlink).  I chose to make a symlink in /usr/local/bin.

**Comment by iancze** [comment]
I added a section in the README about this possible extra step depending on how users have installed Julia. Thanks for the heads up.
