### ISSUE TITLE
Install instructions list IJulia under python packages

### ISSUE THREAD

**Issue by elnjensen** [iancze/DiskJockey#14]
The installation instructions list IJulia under required Python packages, implying that it can be installed via a Python package manager.  But it seems the current way to install it is within julia, via 

Pkg.add("IJulia")

Thanks Ian!

**Comment by iancze** [comment]
`IJulia` is now listed as a requirement of the package, so it now should be installed when you install the DiskJockey package. If you already have DiskJockey installed, you'll have to use 

    Pkg.add("IJulia") 

as you mention.
