### ISSUE TITLE
Error initializing model with test HDF5 dataset

### ISSUE THREAD

**Issue by elnjensen** [iancze/DiskJockey#15]
When I try to initialize a model using the test dataset provided, I get an error:

ERROR: LoadError: Error opening object //freqs

Looks like a problem reading the visibility file. 
I checked the MD5 checksum of the data.hdf5 file, and it matches that on Figshare. 

Full error trace is attached. 
[initialize_output.txt](https://github.com/iancze/DiskJockey/files/203618/initialize_output.txt)

**Comment by iancze** [comment]
I recently updated the [UVHDF5 format](https://github.com/Astrochem/UVHDF5) to include flagged visibilities. They are masked out during the fitting stage, but you can still synthesize model points at flagged (u,v) locations, say if you later wanted to image a model in CASA.  The file on figshare is a stale older format. I will re-export the AK Sco dataset and upload it to figshare.

**Comment by iancze** [comment]
The download link in the cookbook should be fixed now, please re-open if you have problems.
