### ISSUE TITLE
note assumptions being made in the image_to_fits script

### ISSUE THREAD

**Issue by j6626** [iancze/DiskJockey#16]
There are a few underlying assumptions in my RADMC image to FITS conversion script that weren't made immediately explicit. 

For example, it assumes that all the channels are evenly spaced in frequency. I would expect this to be the typical use case, but RADMC does allow you to choose your wavelength spacings arbitrarily. 

I've also only used it on gas images, not dust.

**Comment by iancze** [comment]
Thanks for the comment and the previous pull request. I added an assert statement to check that the channel widths are equal to within 1% [here](https://github.com/iancze/DiskJockey/blob/master/scripts/DJ_image_to_FITS.py#L60).

I'm going to close this issue for now, but please re-open if you have other comments on this script.
