### ISSUE TITLE
plot_walkers.py missing

### ISSUE THREAD

**Issue by elnjensen** [iancze/DiskJockey#23]
Was deleting `plot_walkers.py` from the devel branch intentional?   Seems to be missing, but is still referenced in `cookbook.md`.  And seems like it would still be useful to have.

**Comment by iancze** [comment]
This has been renamed `DJ_plot_walkers.py` for consitency and less namespace clutter on the user's path. I forgot to add this script back to the repo, however. It should be there now.

**Comment by elnjensen** [comment]
OK, ignore the PR I just made then.  I'll look at the new file and PR my minor changes if needed.  Thx.

**Comment by iancze** [comment]
That sounds great, thanks! Sorry for the mixup.
