### ISSUE TITLE
FITS conversion center pixel values

### ISSUE THREAD

**Issue by j6626** [iancze/DiskJockey#25]
The center pixel values that I set for the header in the FITS conversion script (CRPIX1 and CRPIX2) should probably be adjusted to be consistent with most conventions (and I also realized it wasn't consistent with the accompanying comment).

Right now it's `header['CRPIX1'] = 0.5*im_nx + 0.5`, but it should probably be something like

```
if im_nx%2==0:
    header['CRPIX1'] = int(0.5*im_nx + 1)
else:
    header['CRPIX1'] = int(0.5*im_nx + 0.5)
````

**Comment by iancze** [comment]
Nice catch. Feel free to initiate a pull request, otherwise I will get around to updating this eventually.

**Comment by j6626** [comment]
So looking closer, it's interesting to note that LIME and CASA don't use the same center pixel convention. I went with the CASA center pixel convention because I assume that this script would generally be used for the sake of feeding into simobserve, but it's worth noting that vis_sample expects the LIME convention.
