### ISSUE TITLE
Julia not finding installed Python modules

### ISSUE THREAD

**Issue by mansdell** [iancze/DiskJockey#28]
Hi,

I just installed Julia and the DiskJockey package without errors. However, when running DJ_initialize.jl --version  I get the following error:

WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiled cache file for module FFTW. Got:
WARNING: Cache file "/o/ansdell/.julia/lib/v0.6/FFTW.ji" not found.
WARNING: eval from module Main to ImageCore:
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/o/ansdell/.julia/v0.6/FFTW/src/FFTW.jl")::Any
  ** incremental compilation may be broken for this module **

But then eventually:

Your DiskJockey scripts are successfully linked.
You are running DiskJockey 0.1.4
Exiting

Then if I run Pkg.test("DiskJockey") I get Python-related errors:

INFO: Testing DiskJockey
/o/ansdell/anaconda3/bin:/o/ansdell/diskjockey/julia/bin/:/o/ansdell/.julia/v0.6/DiskJockey/scripts:/o/ansdell/anaconda3/bin:/o/ansdell/diskjockey/julia/bin/:/o/ansdell/.julia/v0.6/DiskJockey/scripts:/usr/lib64/mpi/gcc/openmpi/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
Current working directory /indirect/o/ansdell/.julia/v0.6/DiskJockey/test
Files in this directory
clean.sh   edit_config.py	ensemble_sampler.jl  interpolation.jl	  plot_rosenbrock.py  runtests.jl
data.hdf5  emcee_rosenbrock.py	initialize.jl	     parameters_fixed.jl  prior.jl	      simple_math.jl
WARNING: No working GUI backend found for matplotlib
ERROR: LoadError: LoadError: InitError: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)

The Python package matplotlib.pyplot could not be found by pyimport. Usually this means
that you did not install matplotlib.pyplot in the Python version being used by PyCall.

PyCall is currently configured to use the Python version at:

/o/ansdell/anaconda3/bin/python

and you should use whatever mechanism you usually use (apt-get, pip, conda,
etcetera) to install the Python package containing the matplotlib.pyplot module.

One alternative is to re-configure PyCall to use a different Python
version on your system: set ENV["PYTHON"] to the path/name of the python
executable you want to use, run Pkg.build("PyCall"), and re-launch Julia.

Another alternative is to configure PyCall to use a Julia-specific Python
distribution via the Conda.jl package (which installs a private Anaconda
Python distribution), which has the advantage that packages can be installed
and kept up-to-date via Julia.  As explained in the PyCall documentation,
set ENV["PYTHON"]="", run Pkg.build("PyCall"), and re-launch Julia. Then,
To install the matplotlib.pyplot module, you can use `pyimport_conda("matplotlib.pyplot", PKG)`,
where PKG is the Anaconda package the contains the module matplotlib.pyplot,
or alternatively you can use the Conda package directly (via
`using Conda` followed by `Conda.add` etcetera).

) <class 'ImportError'>
ImportError("/lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /o/ansdell/anaconda3/lib/python3.6/site-packages/matplotlib/../../.././libpng16.so.16)",)
  File "/o/ansdell/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/o/ansdell/anaconda3/lib/python3.6/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/o/ansdell/anaconda3/lib/python3.6/site-packages/matplotlib/contour.py", line 21, in <module>
    import matplotlib.font_manager as font_manager
  File "/o/ansdell/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir

Stacktrace:
 [1] pyerr_check at /o/ansdell/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /o/ansdell/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /o/ansdell/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] pyimport(::String) at /o/ansdell/.julia/v0.6/PyCall/src/PyCall.jl:374
 [5] __init__() at /o/ansdell/.julia/v0.6/PyPlot/src/init.jl:184
 [6] _include_from_serialized(::String) at ./loading.jl:157
 [7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [8] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
 [9] _require(::Symbol) at ./loading.jl:441
 [10] require(::Symbol) at ./loading.jl:405
 [11] include_from_node1(::String) at ./loading.jl:576
 [12] include(::String) at ./sysimg.jl:14
 [13] include_from_node1(::String) at ./loading.jl:576
 [14] include(::String) at ./sysimg.jl:14
 [15] process_options(::Base.JLOptions) at ./client.jl:305
 [16] _start() at ./client.jl:371
during initialization of module PyPlot
while loading /indirect/o/ansdell/.julia/v0.6/DiskJockey/test/interpolation.jl, in expression starting on line 2
while loading /indirect/o/ansdell/.julia/v0.6/DiskJockey/test/runtests.jl, in expression starting on line 13
==============================================[ ERROR: DiskJockey ]==============================================

failed process: Process(`/indirect/o/ansdell/diskjockey/julia/bin/julia -Cx86-64 -J/indirect/o/ansdell/diskjockey/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /indirect/o/ansdell/.julia/v0.6/DiskJockey/test/runtests.jl`, ProcessExited(1)) [1]

=================================================================================================================
ERROR: DiskJockey had test errors

It seems the error is related to not being able to find the PyPlot installation, which is already installed on the machine. I have already checked that PyCall is configured to the right Python executable. I also tried re-setting ENV["PYTHON"] to the python executable, running Pkg.build("PyCall"), and re-launching Julia. 

Any other ideas?

Cheers,
Megan

**Comment by iancze** [comment]
Hi Megan,

Thanks for trying the package, and my apologies that the process had some hiccups. The first block of warning messages are related to the FFTW package, used to do the FFTs. As far as I can tell, these are unavoidable but should not be present the next time you use the package. 

You are correct that the string of error messages that follow pertain to the installation and usage of the julia packages that wrap matplotlib, which are PyPlot.jl and PyCall.jl. It may be easiest to debug these separately outside of DiskJockey.

If you launch julia and try

julia > using PyPlot

what happens? I believe that the suggestions that are spit out in the previous warning message (ENV["PYTHON"]) are a trick to convince PyCall.jl to download it's own private copy of anaconda python and link to that. I've had more success trying to link it to my own local anaconda distribution, but this may work too. There are some more tips in the PyPlot.jl documentation (https://github.com/JuliaPy/PyPlot.jl), which may be helpful. Please let me know if any of this helps.

Best,

Ian

**Comment by mansdell** [comment]
Hi Ian,

I found a fix to the underlying problem, which is that Julia is failing to load PyPlot due to multiple installations of the libz Python module. It's a bit confusing because the majority of the Julia error focuses on the matplotlib installation, but there is actually an "ImportError" for libz about halfway down the error message.

I found the solution [here](https://github.com/JuliaPy/PyPlot.jl/issues/151), which suggests several fixes. The one that worked for me was putting the following line into my .bash_profile file:

export LD_LIBRARY_PATH="/o/ansdell/anaconda3/lib:$LD_LIBRARY_PATH"

There are some concerns about automatically changing this environment variable, as it can fix the PyPlot issue, but break other packages. So, an alternative is to set the path in the command line before starting Julia:

>LD_PRELOAD=/o/ansdell/anaconda3/lib/libz.so.1 
>julia

Both options worked for me in terms of successfully running Pkg.test("DiskJockey").

Best,
Megan

**Comment by iancze** [comment]
Thanks for solving this, Megan. 

At least as of now, this still continues to be a problem when dealing with PyCall / PyPlot and an Anaconda installation on certain machines. As you pointed out, this is because conda.jl is bringing along it's own libz libraries that are somehow not correctly loaded when Julia loads Python to call Matploblib, but are correctly loaded if you just loaded Python directly. 

Nearly two years later I haven't found a better solution, so I'll keep this issue open for future reference.

**Comment by iancze** [comment]
I haven't run into this issue in a few months, and the automated continuous integration I recently set up seems to pass as long as python/matplotlib are installed on the user's system prior to installing DiskJockey. I'm going to close this for now but please re-raise if you encounter this using the updated codebase. Thanks.
