### ISSUE TITLE
To choose channels of the visibility

### ISSUE THREAD

**Issue by jkdiazb** [iancze/DiskJockey#37]
Hi!
I have a question. It is possible to adjust some parameter in order to choose the channels that I want to use in DiskJockey?
In particular, I would like to use a specific region/range of the spectrum as "template", but I don't know if there is this option, or if I should choose the channels using mstransform and thus erase the channels that I don't want to use.
I was looking for something about this in visibilities.jl but I was unlucky.

Thanks in advance!
Cheers, 
Javiera

**Comment by iancze** [comment]
Dear Javiera,

By default, DiskJockey will use all channels of the visibilities that you provide it to calculate the likelihood function via the `venus.jl` script. It is not yet properly documented, but there is the possibility to exclude velocity ranges from the likelihood calculation by adding the following lines to your `config.yaml`

```
# Are there any velocity ranges of the dataset to exclude? If so, provide them here.
exclude: [[4.0, 7.5]]
```
where exclude is a list of velocity ranges to exclude. The code that actually calculates the exclusion mask in `venus.jl` is here: https://github.com/iancze/DiskJockey/blob/master/scripts/venus.jl#L128

If you are just trying to truncate end regions from your measurement set to prepare for fitting, then all of this data processing is probably best handled in CASA via `mstransform` or `cvel2`, like you mentioned.

Hope this is helpful,

Ian

**Comment by jkdiazb** [comment]
Thank you very much!
I will use that parameter.

Javiera

**Comment by iancze** [comment]
Great, glad this is helpful. Closing for now but please reopen the issue if you have any further questions.
