### ISSUE TITLE
Path to download RADMC-3D in build.jl is outdated

### ISSUE THREAD

**Issue by j6626** [iancze/DiskJockey#38]
DiskJockey tries to download RADMC-3D from http://www.ita.uni-heidelberg.de/~dullemond/software/radmc-3d/radmc-3d_v0.41_07.07.17.zip, which no longer works. RADMC-3D has been moved to https://github.com/dullemond/radmc3d-2.0 (newest version) or https://github.com/dullemond/radmc3d-0.41 (version matching the one currently used by DiskJockey).

**Comment by iancze** [comment]
Closed by #39
